//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LaptrinhWeb_BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietgiohang
    {
        public string MaGiohang { get; set; }
        public string Masach { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual giohang giohang { get; set; }
        public virtual sach sach { get; set; }
    }
}
