//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LaptrinhWeb_BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giohang
    {
        public giohang()
        {
            this.chitietgiohangs = new HashSet<chitietgiohang>();
        }
    
        public string MaGiohang { get; set; }
        public string TenDN { get; set; }
        public Nullable<System.DateTime> ngaymua { get; set; }
    
        public virtual ICollection<chitietgiohang> chitietgiohangs { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
