//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LaptrinhWeb_BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.giohangs = new HashSet<giohang>();
        }
    
        public string TenDN { get; set; }
        public string Matkhau { get; set; }
        public string HotenKH { get; set; }
        public string DiachiKH { get; set; }
        public string DienthoaiKH { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string Email { get; set; }
        public Nullable<int> Quyen { get; set; }
    
        public virtual ICollection<giohang> giohangs { get; set; }
    }
}
