//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LaptrinhWeb_BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaxuatban
    {
        public nhaxuatban()
        {
            this.saches = new HashSet<sach>();
        }
    
        public string MaNXB { get; set; }
        public string TenNXB { get; set; }
    
        public virtual ICollection<sach> saches { get; set; }
    }
}
