#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LaptrinhWeb_BanSach.Models1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LaptrinhWeb_BTL_Bansach")]
	public partial class DataProductContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    #endregion
		
		public DataProductContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LaptrinhWeb_BTL_BansachConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataProductContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProductContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProductContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProductContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Masach;
		
		private string _Tensach;
		
		private System.Nullable<double> _Dongia;
		
		private string _Donvitinh;
		
		private string _Mota;
		
		private string _Hinhminhhoa;
		
		private System.Nullable<System.DateTime> _Ngaycapnhat;
		
		private System.Nullable<int> _Soluongban;
		
		private System.Nullable<int> _Solanxem;
		
		private string _tentacgia;
		
		private string _MaCD;
		
		private string _MaNXB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasachChanging(string value);
    partial void OnMasachChanged();
    partial void OnTensachChanging(string value);
    partial void OnTensachChanged();
    partial void OnDongiaChanging(System.Nullable<double> value);
    partial void OnDongiaChanged();
    partial void OnDonvitinhChanging(string value);
    partial void OnDonvitinhChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnHinhminhhoaChanging(string value);
    partial void OnHinhminhhoaChanged();
    partial void OnNgaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapnhatChanged();
    partial void OnSoluongbanChanging(System.Nullable<int> value);
    partial void OnSoluongbanChanged();
    partial void OnSolanxemChanging(System.Nullable<int> value);
    partial void OnSolanxemChanged();
    partial void OntentacgiaChanging(string value);
    partial void OntentacgiaChanged();
    partial void OnMaCDChanging(string value);
    partial void OnMaCDChanged();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    #endregion
		
		public sach()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masach", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Masach
		{
			get
			{
				return this._Masach;
			}
			set
			{
				if ((this._Masach != value))
				{
					this.OnMasachChanging(value);
					this.SendPropertyChanging();
					this._Masach = value;
					this.SendPropertyChanged("Masach");
					this.OnMasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensach", DbType="NVarChar(100)")]
		public string Tensach
		{
			get
			{
				return this._Tensach;
			}
			set
			{
				if ((this._Tensach != value))
				{
					this.OnTensachChanging(value);
					this.SendPropertyChanging();
					this._Tensach = value;
					this.SendPropertyChanged("Tensach");
					this.OnTensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Float")]
		public System.Nullable<double> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(10)")]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this.OnDonvitinhChanging(value);
					this.SendPropertyChanging();
					this._Donvitinh = value;
					this.SendPropertyChanged("Donvitinh");
					this.OnDonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhminhhoa", DbType="NVarChar(100)")]
		public string Hinhminhhoa
		{
			get
			{
				return this._Hinhminhhoa;
			}
			set
			{
				if ((this._Hinhminhhoa != value))
				{
					this.OnHinhminhhoaChanging(value);
					this.SendPropertyChanging();
					this._Hinhminhhoa = value;
					this.SendPropertyChanged("Hinhminhhoa");
					this.OnHinhminhhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycapnhat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Ngaycapnhat
		{
			get
			{
				return this._Ngaycapnhat;
			}
			set
			{
				if ((this._Ngaycapnhat != value))
				{
					this.OnNgaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._Ngaycapnhat = value;
					this.SendPropertyChanged("Ngaycapnhat");
					this.OnNgaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongban", DbType="Int")]
		public System.Nullable<int> Soluongban
		{
			get
			{
				return this._Soluongban;
			}
			set
			{
				if ((this._Soluongban != value))
				{
					this.OnSoluongbanChanging(value);
					this.SendPropertyChanging();
					this._Soluongban = value;
					this.SendPropertyChanged("Soluongban");
					this.OnSoluongbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solanxem", DbType="Int")]
		public System.Nullable<int> Solanxem
		{
			get
			{
				return this._Solanxem;
			}
			set
			{
				if ((this._Solanxem != value))
				{
					this.OnSolanxemChanging(value);
					this.SendPropertyChanging();
					this._Solanxem = value;
					this.SendPropertyChanged("Solanxem");
					this.OnSolanxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentacgia", DbType="NVarChar(80)")]
		public string tentacgia
		{
			get
			{
				return this._tentacgia;
			}
			set
			{
				if ((this._tentacgia != value))
				{
					this.OntentacgiaChanging(value);
					this.SendPropertyChanging();
					this._tentacgia = value;
					this.SendPropertyChanged("tentacgia");
					this.OntentacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="VarChar(10)")]
		public string MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="VarChar(10)")]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
